services:
  gitlab-runner-windows:
    image: 'mcr.microsoft.com/windows/servercore:ltsc2022'
    entrypoint: powershell -NoProfile -NonInteractive -Command
    command: "Write-Host 'Hello World'"

    deploy:
      mode: global
      placement:
        constraints: [ node.platform.os == windows ]
